# CI build for developer builds.

variables:
- template: config/settings.yml
- name: packagingEnabled
  value: false

jobs:
- job: CodeValidation
  pool:
    vmImage: windows-2019
  steps:
  - template: templates/validation.yml

- job: DeveloperValidation
  timeoutInMinutes: 120
  pool:
    name: On-Prem Unity
    demands:
    - ${{ variables.Unity2018Version }}
    - COG-UnityCache-WUS2-01
    - SDK_18362 -equals TRUE
  steps:
  - template: templates/ci-common.yml
    parameters:
      packagingEnabled: false
      UnityVersion: $(Unity2018Version)
